[package]
name = "sextant-cli"
description = "The sextant command-line interface."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "sextant"
path = "src/main.rs"

[dependencies]
clap.workspace = true
sextant-engine.workspace = true

[lints]
workspace = true
