//! 010 Editor binary template (`.bt`) exporter (FR-37).
//!
//! 010 templates are a C dialect: `typedef struct`s of typed members, with the
//! root mapped by declaring a variable. Each IR [`Structure`] becomes a struct,
//! nested struct kinds become their own typedef defined before use, and a
//! derived size or count references the governing member by name. Variable-count
//! arrays that run to end use a `while(!FEof())` loop, which 010 supports inside
//! a struct body.
//!
//! Constructs 010 does not enforce (a constant, a checksum) are recorded as
//! comments; the structure still parses.

use std::fmt::Write as _;

use sextant_ir::{
    Constraint, CountRule, Endianness, Field, Format, Kind, Signedness, SizeRule, StringEncoding,
    Structure,
};

use crate::naming::{Allocator, comment_text, pascal, snake};

/// Render `format` as a complete 010 Editor `.bt` template.
#[must_use]
pub(crate) fn export(format: &Format) -> String {
    let mut ctx = Ctx {
        defs: Vec::new(),
        alloc: Allocator::new(),
        endianness: format.endianness,
    };

    // Enums first; they are referenced by member type.
    let mut enum_defs = String::new();
    for (name, def) in &format.enums {
        let type_name = pascal(name, "Enum");
        let underlying = bt_int(def.width.unwrap_or(4), Signedness::Unsigned);
        let _ = writeln!(enum_defs, "typedef enum <{underlying}> {{");
        let mut variants = Vec::new();
        for variant in &def.variants {
            variants.push(format!(
                "    {} = {}",
                pascal(&variant.name, "VALUE"),
                variant.value
            ));
        }
        enum_defs.push_str(&variants.join(",\n"));
        let _ = writeln!(enum_defs, "\n}} {type_name};\n");
    }

    // Render the root body, which appends any dependency typedefs to `defs`.
    let root_body = ctx.render_body(&format.root, 1);
    let root_var = snake(&format.name, "file");

    let mut out = String::new();
    out.push_str("//------------------------------------------------\n");
    out.push_str("// Generated by Sextant. Edit freely.\n");
    out.push_str("//------------------------------------------------\n");
    let _ = writeln!(out, "{}();", endian_call(format.endianness));
    out.push('\n');
    out.push_str(&enum_defs);
    for def in &ctx.defs {
        out.push_str(def);
        out.push('\n');
    }
    out.push_str("struct {\n");
    out.push_str(&root_body);
    let _ = writeln!(out, "}} {root_var};");
    out
}

/// Mutable state for the recursive render: the typedefs in dependency order, the
/// type-name allocator, and the default byte order.
struct Ctx {
    defs: Vec<String>,
    alloc: Allocator,
    endianness: Endianness,
}

impl Ctx {
    /// Define a `typedef struct` for `structure`, emitting dependency typedefs
    /// first, and return its name.
    fn define_struct(&mut self, name_hint: &str, fallback: &str, structure: &Structure) -> String {
        let type_name = self.alloc.allocate(&pascal(name_hint, fallback));
        let body = self.render_body(structure, 1);
        let block = format!("typedef struct {{\n{body}}} {type_name};\n");
        self.defs.push(block);
        type_name
    }

    /// Render a structure body (member declarations) at `indent` levels.
    fn render_body(&mut self, structure: &Structure, indent: usize) -> String {
        let pad = "    ".repeat(indent);
        let mut out = String::new();
        for (index, field) in structure.fields.iter().enumerate() {
            for line in self.member_lines(field, index) {
                let _ = writeln!(out, "{pad}{line}");
            }
        }
        out
    }

    /// The declaration line(s) for one field, including any leading comments and
    /// endianness wrapping.
    fn member_lines(&mut self, field: &Field, index: usize) -> Vec<String> {
        let name = member_name(field, index);
        let mut lines = Vec::new();
        if let Some(comment) = constant_comment(field) {
            lines.push(comment);
        }
        if let Some(note) = checksum_comment(field) {
            lines.push(note);
        }

        let override_order = field_endianness(&field.kind);
        let wrap = match override_order {
            Some(order) if order != self.endianness => Some(order),
            _ => None,
        };
        if let Some(order) = wrap {
            lines.push(format!("{}();", endian_call(order)));
        }

        match &field.kind {
            Kind::Integer { width, signed, .. } => {
                lines.push(format!("{} {name};", bt_int(*width, *signed)));
            }
            Kind::Enum { enum_ref, .. } => {
                lines.push(format!("{} {name};", pascal(enum_ref, "Enum")));
            }
            Kind::Bytes | Kind::Opaque => {
                lines.push(format!(
                    "ubyte {name}{};",
                    self.size_suffix(field.size.as_ref())
                ));
            }
            Kind::String { encoding } => {
                let (elem, divisor) = string_element(*encoding);
                lines.push(format!(
                    "{elem} {name}{};",
                    self.string_suffix(field.size.as_ref(), divisor)
                ));
            }
            Kind::Struct { structure } => {
                let type_name = self.define_struct(
                    field.name.as_deref().unwrap_or("Inner"),
                    "Inner",
                    structure,
                );
                lines.push(format!("{type_name} {name};"));
            }
            Kind::Array { element, count } => {
                lines.extend(self.array_member(&name, element, count));
            }
        }

        if wrap.is_some() {
            // Restore the default order after an overridden field.
            lines.push(format!("{}();", endian_call(self.endianness)));
        }
        lines
    }

    /// Render an array member, either as a sized declaration or a loop.
    fn array_member(&mut self, name: &str, element: &Field, count: &CountRule) -> Vec<String> {
        // A fixed-width integer or enum element is emitted inline. Every other
        // element (a struct, a sized bytes, opaque, or string field, or a nested
        // array) is wrapped in a generated struct so its own size rule and
        // layout survive instead of collapsing to a single scalar.
        let element_type = match &element.kind {
            Kind::Struct { structure } => self.define_struct(
                element.name.as_deref().unwrap_or("Element"),
                "Element",
                structure,
            ),
            Kind::Integer { width, signed, .. } => bt_int(*width, *signed),
            Kind::Enum { enum_ref, .. } => pascal(enum_ref, "Enum"),
            Kind::Bytes | Kind::Opaque | Kind::String { .. } | Kind::Array { .. } => {
                let wrapper = Structure::new(vec![element.clone()]);
                self.define_struct(
                    element.name.as_deref().unwrap_or("Element"),
                    "Element",
                    &wrapper,
                )
            }
        };

        let body = match count {
            CountRule::Fixed { count } => vec![format!("{element_type} {name}[{count}];")],
            CountRule::FromField { count_field } => vec![format!(
                "{element_type} {name}[{}];",
                snake(count_field.as_str(), "count")
            )],
            CountRule::ToEnd => vec![
                "while(!FEof()) {".to_owned(),
                format!("    {element_type} {name};"),
                "}".to_owned(),
            ],
            CountRule::BoundedBy { length_field } => vec![
                format!(
                    "local int64 _{name}_end = FTell() + {};",
                    snake(length_field.as_str(), "len")
                ),
                format!("while(FTell() < _{name}_end) {{"),
                format!("    {element_type} {name};"),
                "}".to_owned(),
            ],
        };

        // An inline integer or enum element with an endianness override is read
        // in the file default order unless the array is wrapped in the matching
        // byte-order call, so wrap it and restore the default afterward.
        match field_endianness(&element.kind).filter(|order| *order != self.endianness) {
            Some(order) => {
                let mut wrapped = vec![format!("{}();", endian_call(order))];
                wrapped.extend(body);
                wrapped.push(format!("{}();", endian_call(self.endianness)));
                wrapped
            }
            None => body,
        }
    }

    /// The array-size suffix for a raw bytes or opaque field.
    fn size_suffix(&self, size: Option<&SizeRule>) -> String {
        match size {
            Some(SizeRule::Fixed { bytes }) => format!("[{bytes}]"),
            Some(SizeRule::Derived { length_field }) => {
                format!("[{}]", snake(length_field.as_str(), "len"))
            }
            Some(SizeRule::ToEnd) | None => "[FileSize() - FTell()]".to_owned(),
            Some(SizeRule::Delimited { terminator, .. }) => {
                let byte = terminator.as_slice().first().copied().unwrap_or(0);
                format!("[FileSize() - FTell()] /* terminator 0x{byte:02x} */")
            }
        }
    }

    /// The array-size suffix for a string field, dividing a byte size by the
    /// element width when the element is wider than a byte.
    fn string_suffix(&self, size: Option<&SizeRule>, divisor: u64) -> String {
        match size {
            Some(SizeRule::Fixed { bytes }) => format!("[{}]", bytes / divisor.max(1)),
            Some(SizeRule::Derived { length_field }) => {
                if divisor <= 1 {
                    format!("[{}]", snake(length_field.as_str(), "len"))
                } else {
                    format!("[{} / {divisor}]", snake(length_field.as_str(), "len"))
                }
            }
            Some(SizeRule::ToEnd) | None | Some(SizeRule::Delimited { .. }) => {
                "[FileSize() - FTell()]".to_owned()
            }
        }
    }
}

/// The 010 integer type for a width and signedness, for example `uint`, `byte`.
fn bt_int(width: u8, signed: Signedness) -> String {
    match (width, signed) {
        (1, Signedness::Unsigned) => "ubyte".to_owned(),
        (1, Signedness::Signed) => "byte".to_owned(),
        (2, Signedness::Unsigned) => "ushort".to_owned(),
        (2, Signedness::Signed) => "short".to_owned(),
        (4, Signedness::Unsigned) => "uint".to_owned(),
        (4, Signedness::Signed) => "int".to_owned(),
        (8, Signedness::Unsigned) => "uint64".to_owned(),
        (8, Signedness::Signed) => "int64".to_owned(),
        // Any other width falls back to a byte array sized below by the caller.
        (other, Signedness::Unsigned) => format!("ubyte[{other}] /* unusual width */"),
        (other, Signedness::Signed) => format!("byte[{other}] /* unusual width */"),
    }
}

/// The 010 element type for a string encoding and the byte width of one element.
fn string_element(encoding: StringEncoding) -> (&'static str, u64) {
    match encoding {
        StringEncoding::Ascii | StringEncoding::Utf8 | StringEncoding::Latin1 => ("char", 1),
        StringEncoding::Utf16Le | StringEncoding::Utf16Be => ("wchar_t", 2),
    }
}

/// The endianness override carried on a field's kind, if any.
fn field_endianness(kind: &Kind) -> Option<Endianness> {
    match kind {
        Kind::Integer { endianness, .. } | Kind::Enum { endianness, .. } => *endianness,
        _ => None,
    }
}

/// A comment recording a constant constraint, since 010 does not enforce one.
fn constant_comment(field: &Field) -> Option<String> {
    field
        .constraints
        .iter()
        .find_map(|constraint| match constraint {
            Constraint::Constant { value } => Some(format!("// constant: {}", value.to_hex())),
            _ => None,
        })
}

/// A comment recording a checksum constraint, since 010 does not verify one.
fn checksum_comment(field: &Field) -> Option<String> {
    field
        .constraints
        .iter()
        .find_map(|constraint| match constraint {
            Constraint::Checksum { spec } => Some(format!(
                "// checksum: {:?} over [{}, {})",
                spec.algorithm,
                comment_text(spec.covered.from.field().as_str()),
                comment_text(spec.covered.to.field().as_str())
            )),
            _ => None,
        })
}

/// The member identifier for a field, synthesizing one when unnamed.
fn member_name(field: &Field, index: usize) -> String {
    match &field.name {
        Some(name) => snake(name, &format!("field_{index}")),
        None => format!("field_{index}"),
    }
}

/// The 010 function call that sets a byte order.
fn endian_call(order: Endianness) -> &'static str {
    match order {
        Endianness::Little => "LittleEndian",
        Endianness::Big => "BigEndian",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tlv_exports_typedefs_and_arrays() {
        let bt = export(&sextant_ir::fixtures::tlv_ground_truth());
        assert!(bt.contains("LittleEndian();"));
        assert!(bt.contains("typedef struct"));
        assert!(bt.contains("ubyte value[length];"));
        assert!(bt.contains("Record records[record_count];"));
        assert!(bt.contains("} tlv;"));
        assert!(bt.contains("// constant: 53544c56"));
    }

    #[test]
    fn png_exports_to_end_loop_and_string() {
        let bt = export(&sextant_ir::fixtures::png_ground_truth());
        assert!(bt.contains("BigEndian();"));
        assert!(bt.contains("while(!FEof()) {"));
        assert!(bt.contains("char chunk_type[4];"));
        assert!(bt.contains("// checksum: Crc32"));
    }

    #[test]
    fn export_is_deterministic() {
        let format = sextant_ir::fixtures::png_ground_truth();
        assert_eq!(export(&format), export(&format));
    }

    use sextant_ir::{Confidence, Metadata};

    /// Build a little-endian format whose root holds one array `items`.
    fn array_format(element: Field, count: CountRule) -> Format {
        let array = Field::new(
            Kind::Array {
                element: Box::new(element),
                count,
            },
            Confidence::CERTAIN,
        )
        .with_name("items");
        Format {
            name: "t".to_owned(),
            endianness: Endianness::Little,
            root: Structure::new(vec![array]),
            enums: Default::default(),
            metadata: Metadata::default(),
        }
    }

    #[test]
    fn array_element_endianness_override_wraps_the_declaration() {
        let element = Field::new(
            Kind::Integer {
                width: 2,
                signed: Signedness::Unsigned,
                endianness: Some(Endianness::Big),
            },
            Confidence::CERTAIN,
        )
        .with_name("word");
        let bt = export(&array_format(element, CountRule::Fixed { count: 3 }));
        // The big-endian array is wrapped in BigEndian()/LittleEndian() calls.
        assert!(
            bt.contains("BigEndian();\n    ushort items[3];"),
            "got:\n{bt}"
        );
    }

    #[test]
    fn sized_byte_array_element_preserves_its_length() {
        let element = Field::new(Kind::Bytes, Confidence::CERTAIN)
            .with_name("blob")
            .with_size(SizeRule::Fixed { bytes: 4 });
        let bt = export(&array_format(element, CountRule::Fixed { count: 2 }));
        // Each element keeps its 4 bytes via a wrapping typedef.
        assert!(bt.contains("ubyte blob[4];"), "got:\n{bt}");
        assert!(bt.contains("items[2];"), "got:\n{bt}");
    }
}
