//! ImHex pattern (`.hexpat`) exporter (FR-37).
//!
//! ImHex patterns are a C-like language: `struct`s of typed members, placed at an
//! absolute address. Each IR [`Structure`] becomes a `struct`, nested struct
//! kinds become their own `struct` types defined before use, arrays become C
//! array members, and a derived size or count references the governing member by
//! name. The root structure is placed at offset zero.
//!
//! Constructs ImHex cannot express (a checksum to verify, a multi-byte
//! terminator) are emitted as comments so the structure still parses while the
//! analyst keeps the context.

use std::fmt::Write as _;

use sextant_ir::{
    Constraint, CountRule, Endianness, Field, Format, Kind, Signedness, SizeRule, StringEncoding,
    Structure,
};

use crate::naming::{Allocator, pascal, snake};

/// Render `format` as a complete ImHex `.hexpat` file.
#[must_use]
pub(crate) fn export(format: &Format) -> String {
    let mut ctx = Ctx {
        defs: Vec::new(),
        alloc: Allocator::new(),
        endianness: format.endianness,
        needs_std_mem: false,
    };

    // Define every enum first; they are referenced by member type.
    let mut enum_defs = String::new();
    for (name, def) in &format.enums {
        let type_name = pascal(name, "Enum");
        let underlying = imhex_int(def.width.unwrap_or(4), Signedness::Unsigned);
        let _ = writeln!(enum_defs, "enum {type_name} : {underlying} {{");
        for variant in &def.variants {
            let _ = writeln!(
                enum_defs,
                "    {} = {},",
                pascal(&variant.name, "VALUE"),
                variant.value
            );
        }
        enum_defs.push_str("};\n\n");
    }

    let root_name = ctx.define_struct(&format.name, "Format", &format.root);
    let root_var = snake(&format.name, "root");

    let mut out = String::new();
    out.push_str("// Generated by Sextant. Edit freely.\n");
    out.push_str(&format!(
        "#pragma endian {}\n",
        endian_word(format.endianness)
    ));
    if ctx.needs_std_mem {
        out.push_str("#pragma once\n");
        out.push_str("import std.mem;\n");
    }
    out.push('\n');
    out.push_str(&enum_defs);
    for def in &ctx.defs {
        out.push_str(def);
        out.push('\n');
    }
    let _ = writeln!(out, "{root_name} {root_var} @ 0x00;");
    out
}

/// Mutable state for the recursive render: the collected struct definitions in
/// dependency order, the type-name allocator, the default byte order, and
/// whether any field needs the standard memory module.
struct Ctx {
    defs: Vec<String>,
    alloc: Allocator,
    endianness: Endianness,
    needs_std_mem: bool,
}

impl Ctx {
    /// Define a `struct` type for `structure`, emitting any dependency types
    /// first, and return its name.
    fn define_struct(&mut self, name_hint: &str, fallback: &str, structure: &Structure) -> String {
        let type_name = self.alloc.allocate(&pascal(name_hint, fallback));
        let mut body = String::new();
        for (index, field) in structure.fields.iter().enumerate() {
            for line in self.member_lines(field, index) {
                let _ = writeln!(body, "    {line}");
            }
        }
        let block = format!("struct {type_name} {{\n{body}}};\n");
        self.defs.push(block);
        type_name
    }

    /// The member declaration line(s) for one field.
    fn member_lines(&mut self, field: &Field, index: usize) -> Vec<String> {
        let name = member_name(field, index);
        let mut lines = Vec::new();
        if let Some(comment) = constant_comment(field) {
            lines.push(comment);
        }
        if let Some(note) = checksum_comment(field) {
            lines.push(note);
        }

        match &field.kind {
            Kind::Integer {
                width,
                signed,
                endianness,
            } => {
                let ty = imhex_int(*width, *signed);
                lines.push(format!(
                    "{}{ty} {name};",
                    self.endian_prefix(*endianness, *width)
                ));
            }
            Kind::Enum {
                enum_ref,
                endianness,
                width,
            } => {
                let ty = pascal(enum_ref, "Enum");
                lines.push(format!(
                    "{}{ty} {name};",
                    self.endian_prefix(*endianness, *width)
                ));
            }
            Kind::Bytes | Kind::Opaque => {
                let size = self.array_size(field.size.as_ref());
                lines.push(format!("u8 {name}{size};"));
            }
            Kind::String { encoding } => {
                let (elem, divisor) = string_element(*encoding);
                let size = self.string_size(field.size.as_ref(), divisor);
                lines.push(format!("{elem} {name}{size};"));
            }
            Kind::Struct { structure } => {
                let type_name = self.define_struct(
                    field.name.as_deref().unwrap_or("Inner"),
                    "Inner",
                    structure,
                );
                lines.push(format!("{type_name} {name};"));
            }
            Kind::Array { element, count } => {
                lines.extend(self.array_member(field, &name, element, count));
            }
        }
        lines
    }

    /// Render an array member: its element type plus a C array suffix derived
    /// from the count rule.
    fn array_member(
        &mut self,
        field: &Field,
        name: &str,
        element: &Field,
        count: &CountRule,
    ) -> Vec<String> {
        let element_type = match &element.kind {
            Kind::Struct { structure } => self.define_struct(
                element.name.as_deref().unwrap_or("Element"),
                "Element",
                structure,
            ),
            Kind::Integer { width, signed, .. } => imhex_int(*width, *signed),
            Kind::Enum { enum_ref, .. } => pascal(enum_ref, "Enum"),
            Kind::String { encoding } => string_element(*encoding).0.to_owned(),
            Kind::Bytes | Kind::Opaque => "u8".to_owned(),
            Kind::Array { .. } => {
                // ImHex cannot declare an array of arrays on one line; wrap the
                // inner array in a generated struct so it stays parseable.
                let wrapper = Structure::new(vec![element.clone()]);
                self.define_struct(field.name.as_deref().unwrap_or("Inner"), "Inner", &wrapper)
            }
        };
        let suffix = match count {
            CountRule::Fixed { count } => format!("[{count}]"),
            CountRule::FromField { count_field } => {
                format!("[{}]", snake(count_field.as_str(), "count"))
            }
            CountRule::ToEnd => {
                self.needs_std_mem = true;
                "[while(!std::mem::eof())]".to_owned()
            }
            CountRule::BoundedBy { length_field } => {
                // Bound the repeat by a byte length relative to the array start.
                format!(
                    "[while($ < addressof({name}) + {})]",
                    snake(length_field.as_str(), "len")
                )
            }
        };
        vec![format!("{element_type} {name}{suffix};")]
    }

    /// The array-size suffix for a raw bytes or opaque field.
    fn array_size(&mut self, size: Option<&SizeRule>) -> String {
        match size {
            Some(SizeRule::Fixed { bytes }) => format!("[{bytes}]"),
            Some(SizeRule::Derived { length_field }) => {
                format!("[{}]", snake(length_field.as_str(), "len"))
            }
            Some(SizeRule::ToEnd) | None => {
                self.needs_std_mem = true;
                "[while(!std::mem::eof())]".to_owned()
            }
            Some(SizeRule::Delimited { terminator, .. }) => {
                // ImHex has no terminator-sized array, so read to end and leave
                // the terminator as a note for the analyst to refine.
                let byte = terminator.as_slice().first().copied().unwrap_or(0);
                self.needs_std_mem = true;
                format!("[while(!std::mem::eof())] /* terminator 0x{byte:02x} */")
            }
        }
    }

    /// The array-size suffix for a string field, dividing a byte size by the
    /// element width when the element is wider than a byte.
    fn string_size(&mut self, size: Option<&SizeRule>, divisor: u64) -> String {
        match size {
            Some(SizeRule::Fixed { bytes }) => format!("[{}]", bytes / divisor.max(1)),
            Some(SizeRule::Derived { length_field }) => {
                if divisor <= 1 {
                    format!("[{}]", snake(length_field.as_str(), "len"))
                } else {
                    format!("[{} / {divisor}]", snake(length_field.as_str(), "len"))
                }
            }
            Some(SizeRule::ToEnd) | None => {
                self.needs_std_mem = true;
                "[while(!std::mem::eof())]".to_owned()
            }
            Some(SizeRule::Delimited { .. }) => {
                self.needs_std_mem = true;
                "[while(!std::mem::eof())]".to_owned()
            }
        }
    }

    /// An endianness prefix (`be ` or `le `) when a field overrides the default,
    /// otherwise empty. A one-byte field never needs one.
    fn endian_prefix(&self, endianness: Option<Endianness>, width: u8) -> String {
        match endianness {
            Some(order) if width > 1 && order != self.endianness => {
                format!("{} ", endian_word(order))
            }
            _ => String::new(),
        }
    }
}

/// The ImHex integer type for a width and signedness, for example `u32`, `s8`.
fn imhex_int(width: u8, signed: Signedness) -> String {
    let bits = u16::from(width.max(1)) * 8;
    match signed {
        Signedness::Unsigned => format!("u{bits}"),
        Signedness::Signed => format!("s{bits}"),
    }
}

/// The ImHex element type for a string encoding and the byte width of one
/// element, so a byte size can be converted to an element count.
fn string_element(encoding: StringEncoding) -> (&'static str, u64) {
    match encoding {
        StringEncoding::Ascii | StringEncoding::Utf8 | StringEncoding::Latin1 => ("char", 1),
        StringEncoding::Utf16Le | StringEncoding::Utf16Be => ("char16", 2),
    }
}

/// A comment recording a constant constraint, since ImHex does not enforce one.
fn constant_comment(field: &Field) -> Option<String> {
    field
        .constraints
        .iter()
        .find_map(|constraint| match constraint {
            Constraint::Constant { value } => Some(format!("// constant: {}", value.to_hex())),
            _ => None,
        })
}

/// A comment recording a checksum constraint, since ImHex does not verify one.
fn checksum_comment(field: &Field) -> Option<String> {
    field
        .constraints
        .iter()
        .find_map(|constraint| match constraint {
            Constraint::Checksum { spec } => Some(format!(
                "// checksum: {:?} over [{}, {})",
                spec.algorithm,
                spec.covered.from.field(),
                spec.covered.to.field()
            )),
            _ => None,
        })
}

/// The member identifier for a field, synthesizing one when unnamed.
fn member_name(field: &Field, index: usize) -> String {
    match &field.name {
        Some(name) => snake(name, &format!("field_{index}")),
        None => format!("field_{index}"),
    }
}

/// The ImHex `#pragma endian` keyword for a byte order.
fn endian_word(order: Endianness) -> &'static str {
    match order {
        Endianness::Little => "little",
        Endianness::Big => "big",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tlv_exports_structs_and_array() {
        let pat = export(&sextant_ir::fixtures::tlv_ground_truth());
        assert!(pat.contains("#pragma endian little"));
        assert!(pat.contains("struct Record"));
        assert!(pat.contains("struct Tlv"));
        // The value is sized by the length member.
        assert!(pat.contains("u8 value[length];"));
        // The records array repeats by the count member.
        assert!(pat.contains("Record records[record_count];"));
        // The root is placed at offset zero.
        assert!(pat.contains("Tlv tlv @ 0x00;"));
        // The magic constant is recorded as a comment.
        assert!(pat.contains("// constant: 53544c56"));
    }

    #[test]
    fn png_exports_to_end_array_with_std_mem() {
        let pat = export(&sextant_ir::fixtures::png_ground_truth());
        assert!(pat.contains("#pragma endian big"));
        assert!(pat.contains("import std.mem;"));
        assert!(pat.contains("Chunk chunks[while(!std::mem::eof())];"));
        assert!(pat.contains("char chunk_type[4];"));
        assert!(pat.contains("// checksum: Crc32"));
    }

    #[test]
    fn export_is_deterministic() {
        let format = sextant_ir::fixtures::tlv_ground_truth();
        assert_eq!(export(&format), export(&format));
    }
}
