//! Kaitai Struct (`.ksy`) exporter, the primary export and cross-validation
//! target (FR-36).
//!
//! The IR is intentionally close to Kaitai semantics (PRD Section 10), so the
//! mapping is direct: a [`Structure`] becomes a `seq`, each [`Field`] an
//! attribute, nested [`Kind::Struct`] kinds become entries under `types`, and
//! named enums become entries under `enums`. The output is a YAML document
//! written by hand (no YAML dependency) so the exact key order and formatting
//! stay under our control and the result is deterministic.
//!
//! Constructs Kaitai cannot express are rendered as `doc` notes rather than
//! dropped silently: a checksum constraint becomes a note (Kaitai does not
//! verify checksums), and a derived field offset becomes a note. The structural
//! shape, the part that lets the spec parse a sample, is always emitted.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use sextant_ir::{
    Constraint, CountRule, Endianness, EnumDef, Field, Format, Kind, SizeRule, StringEncoding,
    Structure,
};

use crate::naming::{Allocator, snake};
use crate::{const_as_u64, sign_letter};

/// Render `format` as a complete Kaitai `.ksy` document.
#[must_use]
pub(crate) fn export(format: &Format) -> String {
    let mut ctx = Ctx {
        types: BTreeMap::new(),
        alloc: Allocator::new(),
        endianness: format.endianness,
    };
    // Reserve the root id so a nested type never collides with it.
    let root_id = ctx.alloc.allocate(&snake(&format.name, "format"));

    let root_seq = ctx.render_seq(&format.root, 1);

    let mut out = String::new();
    out.push_str("# Generated by Sextant. Edit freely.\n");
    out.push_str("meta:\n");
    let _ = writeln!(out, "  id: {root_id}");
    let _ = writeln!(out, "  endian: {}", endian_word(format.endianness));
    if let Some(description) = &format.metadata.description {
        let _ = writeln!(out, "  title: {}", yaml_scalar(description));
    }
    out.push_str("seq:\n");
    out.push_str(&root_seq);

    if !ctx.types.is_empty() {
        out.push_str("types:\n");
        for (name, body) in &ctx.types {
            let _ = writeln!(out, "  {name}:");
            out.push_str("    seq:\n");
            out.push_str(body);
        }
    }

    let enums = render_enums(&format.enums);
    if !enums.is_empty() {
        out.push_str("enums:\n");
        out.push_str(&enums);
    }

    out
}

/// Mutable state threaded through the recursive render: the collected named
/// types, the type-name allocator, and the format default endianness.
struct Ctx {
    types: BTreeMap<String, String>,
    alloc: Allocator,
    endianness: Endianness,
}

impl Ctx {
    /// Render a structure's fields as a `seq` block indented at `indent` levels
    /// of two spaces.
    fn render_seq(&mut self, structure: &Structure, indent: usize) -> String {
        let mut out = String::new();
        for (index, field) in structure.fields.iter().enumerate() {
            self.render_field(field, index, indent, &mut out);
        }
        out
    }

    /// Render one field as a `seq` attribute (a `- id:` entry plus its keys).
    fn render_field(&mut self, field: &Field, index: usize, indent: usize, out: &mut String) {
        let pad = "  ".repeat(indent);
        let id = field_id(field, index);
        let mut attrs: Vec<(String, String)> = Vec::new();

        match &field.kind {
            Kind::Integer {
                width,
                signed,
                endianness,
            } => {
                attrs.push(("type".to_owned(), int_type(*width, *signed, *endianness)));
                if let Some(value) = integer_constant(field, *width, endianness, self.endianness) {
                    attrs.push(("valid".to_owned(), value.to_string()));
                }
            }
            Kind::Enum {
                enum_ref,
                width,
                endianness,
            } => {
                attrs.push((
                    "type".to_owned(),
                    int_type(*width, sextant_ir::Signedness::Unsigned, *endianness),
                ));
                attrs.push(("enum".to_owned(), snake(enum_ref, "values")));
            }
            Kind::Bytes => self.bytes_attrs(field, &mut attrs),
            Kind::Opaque => self.bytes_attrs(field, &mut attrs),
            Kind::String { encoding } => {
                if let Some(contents) = constant_contents(field) {
                    attrs.push(("contents".to_owned(), contents));
                } else {
                    attrs.push(("type".to_owned(), "str".to_owned()));
                    self.size_attrs(field.size.as_ref(), &mut attrs);
                    attrs.push(("encoding".to_owned(), encoding_name(*encoding).to_owned()));
                }
            }
            Kind::Struct { structure } => {
                let type_name = self.define_type(field, index, structure);
                attrs.push(("type".to_owned(), type_name));
            }
            Kind::Array { element, count } => {
                self.array_attrs(element, count, &mut attrs);
            }
        }

        for note in self.field_notes(field) {
            attrs.push(("doc".to_owned(), yaml_scalar(&note)));
        }

        write_attrs(out, &pad, &id, &attrs);
    }

    /// Emit the size attributes for a raw bytes or opaque field.
    fn bytes_attrs(&mut self, field: &Field, attrs: &mut Vec<(String, String)>) {
        if let Some(contents) = constant_contents(field) {
            attrs.push(("contents".to_owned(), contents));
            return;
        }
        self.size_attrs(field.size.as_ref(), attrs);
    }

    /// Translate a [`SizeRule`] into Kaitai `size` or `size-eos` keys.
    fn size_attrs(&mut self, size: Option<&SizeRule>, attrs: &mut Vec<(String, String)>) {
        match size {
            Some(SizeRule::Fixed { bytes }) => {
                attrs.push(("size".to_owned(), bytes.to_string()));
            }
            Some(SizeRule::Derived { length_field }) => {
                attrs.push(("size".to_owned(), snake(length_field.as_str(), "len")));
            }
            Some(SizeRule::ToEnd) => {
                attrs.push(("size-eos".to_owned(), "true".to_owned()));
            }
            Some(SizeRule::Delimited {
                terminator,
                include_terminator,
            }) => {
                if terminator.len() == 1 {
                    attrs.push((
                        "terminator".to_owned(),
                        format!("0x{:02x}", terminator.as_slice()[0]),
                    ));
                    attrs.push(("include".to_owned(), include_terminator.to_string()));
                } else {
                    // Kaitai's terminator is a single byte. A multi-byte
                    // terminator cannot be expressed directly, so read to the
                    // end of the stream and leave a note for the analyst.
                    attrs.push(("size-eos".to_owned(), "true".to_owned()));
                    attrs.push((
                        "doc".to_owned(),
                        yaml_scalar(&format!(
                            "delimited by terminator 0x{}; adjust by hand",
                            terminator.to_hex()
                        )),
                    ));
                }
            }
            None => {}
        }
    }

    /// Emit the type and repeat attributes for an array field.
    fn array_attrs(
        &mut self,
        element: &Field,
        count: &CountRule,
        attrs: &mut Vec<(String, String)>,
    ) {
        // The element type goes on the array attribute itself.
        match &element.kind {
            Kind::Struct { structure } => {
                let type_name = self.define_type(element, 0, structure);
                attrs.push(("type".to_owned(), type_name));
            }
            Kind::Integer {
                width,
                signed,
                endianness,
            } => attrs.push(("type".to_owned(), int_type(*width, *signed, *endianness))),
            Kind::Enum {
                enum_ref,
                width,
                endianness,
            } => {
                attrs.push((
                    "type".to_owned(),
                    int_type(*width, sextant_ir::Signedness::Unsigned, *endianness),
                ));
                attrs.push(("enum".to_owned(), snake(enum_ref, "values")));
            }
            Kind::String { encoding } => {
                attrs.push(("type".to_owned(), "str".to_owned()));
                self.size_attrs(element.size.as_ref(), attrs);
                attrs.push(("encoding".to_owned(), encoding_name(*encoding).to_owned()));
            }
            Kind::Bytes | Kind::Opaque => {
                self.size_attrs(element.size.as_ref(), attrs);
            }
            Kind::Array { .. } => {
                // Kaitai cannot nest a repeat directly on one attribute; wrap the
                // inner array in a generated single-field type.
                let type_name = self.wrap_element(element);
                attrs.push(("type".to_owned(), type_name));
            }
        }

        match count {
            CountRule::Fixed { count } => {
                attrs.push(("repeat".to_owned(), "expr".to_owned()));
                attrs.push(("repeat-expr".to_owned(), count.to_string()));
            }
            CountRule::FromField { count_field } => {
                attrs.push(("repeat".to_owned(), "expr".to_owned()));
                attrs.push((
                    "repeat-expr".to_owned(),
                    snake(count_field.as_str(), "count"),
                ));
            }
            CountRule::BoundedBy { length_field } => {
                // Read the elements inside a substream sized by the length field.
                attrs.push(("size".to_owned(), snake(length_field.as_str(), "len")));
                attrs.push(("repeat".to_owned(), "eos".to_owned()));
            }
            CountRule::ToEnd => {
                attrs.push(("repeat".to_owned(), "eos".to_owned()));
            }
        }
    }

    /// Define a named Kaitai type for a struct kind and return its name.
    fn define_type(&mut self, field: &Field, index: usize, structure: &Structure) -> String {
        let base = field
            .name
            .as_deref()
            .map_or_else(|| format!("type_{index}"), |name| snake(name, "type"));
        let type_name = self.alloc.allocate(&base);
        // Reserve the name before rendering the body so a recursive or repeated
        // nested type does not reuse it.
        self.types.insert(type_name.clone(), String::new());
        let body = self.render_seq(structure, 3);
        self.types.insert(type_name.clone(), body);
        type_name
    }

    /// Wrap an array-of-array element in a generated single-field type so Kaitai
    /// can carry the inner repeat.
    fn wrap_element(&mut self, element: &Field) -> String {
        let base = element
            .name
            .as_deref()
            .map_or_else(|| "inner".to_owned(), |name| snake(name, "inner"));
        let type_name = self.alloc.allocate(&base);
        self.types.insert(type_name.clone(), String::new());
        let wrapper = Structure::new(vec![element.clone()]);
        let body = self.render_seq(&wrapper, 3);
        self.types.insert(type_name.clone(), body);
        type_name
    }

    /// Human-readable notes that do not change parsing: the role, and any
    /// constraint Kaitai does not enforce.
    fn field_notes(&self, field: &Field) -> Vec<String> {
        let mut notes = Vec::new();
        if let Some(role) = field.role {
            notes.push(format!("role: {}", role_word(role)));
        }
        for constraint in &field.constraints {
            if let Constraint::Checksum { spec } = constraint {
                notes.push(format!(
                    "checksum: {:?} over [{}, {})",
                    spec.algorithm,
                    spec.covered.from.field(),
                    spec.covered.to.field()
                ));
            }
        }
        if field.offset.is_some() {
            notes.push("has an explicit offset; verify positioning by hand".to_owned());
        }
        notes
    }
}

/// Render the top-level `enums` block.
fn render_enums(enums: &BTreeMap<String, EnumDef>) -> String {
    let mut out = String::new();
    for (name, def) in enums {
        let _ = writeln!(out, "  {}:", snake(name, "values"));
        for variant in &def.variants {
            let _ = writeln!(
                out,
                "    {}: {}",
                variant.value,
                snake(&variant.name, "value")
            );
        }
    }
    out
}

/// Write a single `seq` attribute: `- id: <id>` then each key indented one more.
fn write_attrs(out: &mut String, pad: &str, id: &str, attrs: &[(String, String)]) {
    let _ = writeln!(out, "{pad}- id: {id}");
    for (key, value) in attrs {
        let _ = writeln!(out, "{pad}  {key}: {value}");
    }
}

/// The Kaitai type string for an integer, for example `u4`, `s2le`, `u1`.
fn int_type(width: u8, signed: sextant_ir::Signedness, endianness: Option<Endianness>) -> String {
    let letter = sign_letter(signed);
    // A one-byte integer has no byte order, so it never takes an endian suffix.
    let suffix = if width <= 1 {
        ""
    } else {
        match endianness {
            Some(Endianness::Big) => "be",
            Some(Endianness::Little) => "le",
            None => "",
        }
    };
    format!("{letter}{width}{suffix}")
}

/// The integer value of a field's constant constraint, if it has one.
fn integer_constant(
    field: &Field,
    width: u8,
    endianness: &Option<Endianness>,
    default: Endianness,
) -> Option<u64> {
    field
        .constraints
        .iter()
        .find_map(|constraint| match constraint {
            Constraint::Constant { value } => {
                Some(const_as_u64(value, width, endianness.unwrap_or(default)))
            }
            _ => None,
        })
}

/// A `contents` flow list for a field with a byte or string constant, if any.
fn constant_contents(field: &Field) -> Option<String> {
    field
        .constraints
        .iter()
        .find_map(|constraint| match constraint {
            Constraint::Constant { value } => {
                let items: Vec<String> = value
                    .as_slice()
                    .iter()
                    .map(|byte| format!("0x{byte:02x}"))
                    .collect();
                Some(format!("[{}]", items.join(", ")))
            }
            _ => None,
        })
}

/// The Kaitai id for a field, synthesizing one when the IR did not name it.
fn field_id(field: &Field, index: usize) -> String {
    match &field.name {
        Some(name) => snake(name, &format!("field_{index}")),
        None => format!("field_{index}"),
    }
}

/// The Kaitai `endian` keyword for a byte order.
fn endian_word(order: Endianness) -> &'static str {
    match order {
        Endianness::Little => "le",
        Endianness::Big => "be",
    }
}

/// The Kaitai `encoding` name for a string encoding.
fn encoding_name(encoding: StringEncoding) -> &'static str {
    match encoding {
        StringEncoding::Ascii => "ASCII",
        StringEncoding::Utf8 => "UTF-8",
        StringEncoding::Utf16Le => "UTF-16LE",
        StringEncoding::Utf16Be => "UTF-16BE",
        StringEncoding::Latin1 => "ISO-8859-1",
    }
}

/// A short word for a role, used only in `doc` notes.
fn role_word(role: sextant_ir::Role) -> &'static str {
    use sextant_ir::Role;
    match role {
        Role::Magic => "magic",
        Role::Version => "version",
        Role::Length => "length",
        Role::Count => "count",
        Role::Offset => "offset",
        Role::Checksum => "checksum",
        Role::Timestamp => "timestamp",
        Role::Flags => "flags",
        Role::Enum => "enum",
        Role::Reserved => "reserved",
        Role::Payload => "payload",
        Role::Unknown => "unknown",
    }
}

/// Quote a YAML scalar so arbitrary text (including colons and `#`) is safe.
/// Single quotes in the text are doubled, as YAML requires.
fn yaml_scalar(text: &str) -> String {
    let escaped = text.replace('\'', "''");
    format!("'{escaped}'")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tlv_exports_expected_structure() {
        let ksy = export(&sextant_ir::fixtures::tlv_ground_truth());
        assert!(ksy.contains("id: tlv"));
        assert!(ksy.contains("endian: le"));
        // The magic is a byte constant rendered as a contents list.
        assert!(ksy.contains("contents: [0x53, 0x54, 0x4c, 0x56]"));
        // The record array repeats by the count field.
        assert!(ksy.contains("repeat: expr"));
        assert!(ksy.contains("repeat-expr: record_count"));
        // The value size is derived from the length field.
        assert!(ksy.contains("size: length"));
        // The record struct became a named type.
        assert!(ksy.contains("types:"));
        assert!(ksy.contains("record:"));
    }

    #[test]
    fn png_exports_chunks_and_crc_note() {
        let ksy = export(&sextant_ir::fixtures::png_ground_truth());
        assert!(ksy.contains("id: png"));
        assert!(ksy.contains("endian: be"));
        assert!(ksy.contains("type: u4"));
        // The to-end chunk array repeats to end of stream.
        assert!(ksy.contains("repeat: eos"));
        // The chunk type string carries its encoding.
        assert!(ksy.contains("type: str"));
        assert!(ksy.contains("encoding: ASCII"));
        // The CRC field cannot be verified in Kaitai, so it is a note.
        assert!(ksy.contains("checksum: Crc32"));
    }

    #[test]
    fn export_is_deterministic() {
        let format = sextant_ir::fixtures::png_ground_truth();
        assert_eq!(export(&format), export(&format));
    }
}
