//! Wireshark Lua dissector (`.lua`) exporter (FR-37).
//!
//! Unlike the declarative targets, a Wireshark dissector is procedural: a
//! function walks the buffer, advancing an `offset` and adding fields to the
//! dissection tree. This exporter generates that function from the IR. Each
//! integer field's value is captured in a local so a later derived size or count
//! can reference it, arrays become loops, and nested structures become subtrees.
//!
//! The dissector is registered as a [`Proto`] but not bound to a port (file
//! formats have none, and protocols arrive in Step 11); a commented example
//! shows how to attach it. Checksums are not verified, matching the other
//! exporters.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use sextant_ir::{
    CountRule, Endianness, EnumDef, Field, Format, Kind, Signedness, SizeRule, StringEncoding,
    Structure,
};

use crate::naming::snake;

/// Render `format` as a complete Wireshark Lua dissector.
#[must_use]
pub(crate) fn export(format: &Format) -> String {
    let proto = snake(&format.name, "format");
    let mut emitter = Gen {
        proto: proto.clone(),
        endianness: format.endianness,
        enums: format.enums.clone(),
        fields: Vec::new(),
        registered: BTreeSet::new(),
        code: String::new(),
        temp: 0,
        limits: vec!["blen".to_owned()],
    };

    // Emit the dissection body first so the field registry is fully populated.
    emitter.emit_struct(&format.root, "subtree", "", 1);
    let body = std::mem::take(&mut emitter.code);

    let mut out = String::new();
    out.push_str("-- Generated by Sextant. Edit freely.\n");
    let _ = writeln!(
        out,
        "local proto_{proto} = Proto(\"{proto}\", \"{proto} (Sextant)\")"
    );
    out.push_str("local f = {}\n");
    for field in &emitter.fields {
        out.push_str(field);
        out.push('\n');
    }
    out.push_str(&format!("proto_{proto}.fields = {{\n"));
    for key in &emitter.field_keys() {
        let _ = writeln!(out, "    f[\"{key}\"],");
    }
    out.push_str("}\n\n");

    let _ = writeln!(out, "function proto_{proto}.dissector(buffer, pinfo, tree)");
    out.push_str("    local blen = buffer:len()\n");
    out.push_str("    if blen == 0 then return end\n");
    let _ = writeln!(out, "    pinfo.cols.protocol = \"{proto}\"");
    let _ = writeln!(
        out,
        "    local subtree = tree:add(proto_{proto}, buffer(), \"{proto}\")"
    );
    out.push_str("    local offset = 0\n");
    out.push_str("    local sextant = {}\n");
    out.push_str("    local sextant_work = 0\n");
    out.push_str(&body);
    out.push_str("end\n\n");

    // When the IR was inferred from a capture, the transport and port are
    // recorded in the format metadata (Step 11). Bind the dissector to that port
    // so it decodes the capture as soon as the script loads. Otherwise leave a
    // commented example, since a file format has no port to attach to.
    match protocol_binding(format) {
        Some((transport, port)) => {
            out.push_str("-- Inferred from a capture: bound to its transport and port.\n");
            let _ = writeln!(
                out,
                "DissectorTable.get(\"{transport}.port\"):add({port}, proto_{proto})"
            );
        }
        None => {
            out.push_str(
                "-- To attach this dissector, register it with a DissectorTable, for example:\n",
            );
            let _ = writeln!(
                out,
                "-- DissectorTable.get(\"udp.port\"):add(0, proto_{proto})"
            );
        }
    }
    out
}

/// The transport and port a protocol IR was inferred from, when the metadata
/// records them (Step 11). Only `tcp` and `udp` name a Wireshark port table.
fn protocol_binding(format: &Format) -> Option<(&'static str, u16)> {
    let transport = match format.metadata.extra.get("protocol.transport")?.as_str() {
        "tcp" => "tcp",
        "udp" => "udp",
        _ => return None,
    };
    let port: u16 = format.metadata.extra.get("protocol.port")?.parse().ok()?;
    Some((transport, port))
}

/// Mutable state for the recursive code generation.
struct Gen {
    proto: String,
    endianness: Endianness,
    enums: BTreeMap<String, EnumDef>,
    fields: Vec<String>,
    registered: BTreeSet<String>,
    code: String,
    temp: usize,
    limits: Vec<String>,
}

impl Gen {
    fn limit(&self) -> &str {
        self.limits.last().map_or("blen", String::as_str)
    }

    fn checked_size(&mut self, expression: &str, indent: usize) -> String {
        let size = self.temp("size");
        self.line(indent, &format!("local {size} = {expression}"));
        self.line(indent, &format!("if {size} < 0 or offset < 0 or {size} > {} - offset then error(\"Sextant: field exceeds enclosing boundary\") end", self.limit()));
        size
    }
    /// Build the value-string table literal for an enum, mapping each variant's
    /// value to its name so Wireshark shows the symbolic meaning, not just the
    /// number. Returns `None` when the enum is unknown or has no variants.
    fn value_string_table(&self, enum_ref: &str) -> Option<String> {
        let def = self.enums.get(enum_ref)?;
        if def.variants.is_empty() {
            return None;
        }
        let entries: Vec<String> = def
            .variants
            .iter()
            .map(|variant| format!("[{}]=\"{}\"", variant.value, lua_escape(&variant.name)))
            .collect();
        Some(format!("{{{}}}", entries.join(", ")))
    }

    /// The registered field keys, in registration order.
    fn field_keys(&self) -> Vec<String> {
        // The registration line is `f["key"] = ...`; recover the key from it.
        self.fields
            .iter()
            .filter_map(|line| {
                let start = line.find('"')? + 1;
                let end = line[start..].find('"')? + start;
                Some(line[start..end].to_owned())
            })
            .collect()
    }

    /// A fresh, unique Lua local name with the given prefix.
    fn temp(&mut self, prefix: &str) -> String {
        self.temp += 1;
        format!("sextant.{prefix}_{}", self.temp)
    }

    /// Append a line of generated Lua at `indent` levels of four spaces.
    fn line(&mut self, indent: usize, text: &str) {
        for _ in 0..indent {
            self.code.push_str("    ");
        }
        // Keep captured values in one per-invocation table. Lua has a small
        // limit on local variables per function, including nested IR structs.
        self.code.push_str(if text.starts_with("local sextant.") {
            &text[6..]
        } else {
            text
        });
        self.code.push('\n');
    }

    /// Register a [`ProtoField`] once, keyed by its dotted path.
    fn register(&mut self, key: &str, ctor: &str) {
        if self.registered.insert(key.to_owned()) {
            self.fields.push(format!("f[\"{key}\"] = {ctor}"));
        }
    }

    /// Emit code dissecting `structure` into the tree item named `parent`, with
    /// dotted-path `prefix` for field keys.
    fn emit_struct(&mut self, structure: &Structure, parent: &str, prefix: &str, indent: usize) {
        let base = self.temp("base");
        self.line(indent, &format!("local {base} = offset"));
        for (index, field) in structure.fields.iter().enumerate() {
            self.emit_field(field, index, parent, prefix, &base, indent);
        }
    }

    /// Emit one field: honor an explicit offset, then dissect by kind.
    fn emit_field(
        &mut self,
        field: &Field,
        index: usize,
        parent: &str,
        prefix: &str,
        base: &str,
        indent: usize,
    ) {
        let name = field_name(field, index);
        let key = join(prefix, &name);

        match &field.offset {
            Some(sextant_ir::FieldOffset::Absolute { bytes }) => {
                self.line(indent, &format!("offset = {base} + {bytes}"));
            }
            Some(sextant_ir::FieldOffset::Derived { offset_field }) => {
                let var = value_var(&join(prefix, &snake(offset_field.as_str(), "off")));
                self.line(indent, &format!("offset = {base} + {var}"));
            }
            None => {}
        }
        self.line(indent, &format!("if offset < {base} or offset > {} then error(\"Sextant: invalid field offset\") end", self.limit()));

        match &field.kind {
            Kind::Struct { structure } => {
                let sub = self.temp("sub");
                let start = self.temp("start");
                let label = lua_escape(&name);
                self.line(indent, &format!("local {start} = offset"));
                self.line(
                    indent,
                    &format!("local {sub} = {parent}:add(buffer(offset), \"{label}\")"),
                );
                self.emit_struct(structure, &sub, &key, indent);
                self.line(indent, &format!("{sub}:set_len(offset - {start})"));
            }
            Kind::Array { element, count } => {
                self.emit_array(&name, &key, element, count, parent, indent);
            }
            _ => self.emit_value(field, &key, &name, parent, prefix, indent),
        }
    }

    /// Emit a leaf field read (integer, enum, bytes, opaque, or string).
    fn emit_value(
        &mut self,
        field: &Field,
        key: &str,
        label: &str,
        parent: &str,
        prefix: &str,
        indent: usize,
    ) {
        match &field.kind {
            Kind::Integer {
                width,
                signed,
                endianness,
            } => self.emit_integer(
                key,
                label,
                *width,
                *signed,
                *endianness,
                None,
                parent,
                indent,
            ),
            Kind::Enum {
                width,
                endianness,
                enum_ref,
            } => self.emit_integer(
                key,
                label,
                *width,
                Signedness::Unsigned,
                *endianness,
                Some(enum_ref.as_str()),
                parent,
                indent,
            ),
            Kind::Bytes | Kind::Opaque => {
                if let Some(SizeRule::Delimited {
                    terminator,
                    include_terminator,
                }) = field.size.as_ref()
                {
                    self.emit_delimited(
                        key,
                        label,
                        false,
                        terminator.as_slice(),
                        *include_terminator,
                        parent,
                        indent,
                    );
                    return;
                }
                let ctor = format!(
                    "ProtoField.bytes(\"{}.{key}\", \"{}\")",
                    self.proto,
                    lua_escape(label)
                );
                self.register(key, &ctor);
                let expression = self.size_expr(field.size.as_ref(), prefix);
                let size = self.checked_size(&expression, indent);
                self.line(
                    indent,
                    &format!("{parent}:add(f[\"{key}\"], buffer(offset, {size}))"),
                );
                self.line(indent, &format!("offset = offset + ({size})"));
            }
            Kind::String { encoding } => {
                if let Some(SizeRule::Delimited {
                    terminator,
                    include_terminator,
                }) = field.size.as_ref()
                {
                    self.emit_delimited(
                        key,
                        label,
                        true,
                        terminator.as_slice(),
                        *include_terminator,
                        parent,
                        indent,
                    );
                    return;
                }
                let ctor = format!(
                    "ProtoField.string(\"{}.{key}\", \"{}\")",
                    self.proto,
                    lua_escape(label)
                );
                self.register(key, &ctor);
                let expression = self.size_expr(field.size.as_ref(), prefix);
                let size = self.checked_size(&expression, indent);
                let adder = if matches!(encoding, StringEncoding::Utf16Le) {
                    "add_le"
                } else {
                    "add"
                };
                self.line(
                    indent,
                    &format!("{parent}:{adder}(f[\"{key}\"], buffer(offset, {size}))"),
                );
                self.line(indent, &format!("offset = offset + ({size})"));
            }
            Kind::Struct { .. } | Kind::Array { .. } => {
                // Composite kinds are handled by emit_field, not emit_value.
            }
        }
    }

    /// Emit an integer or enum read, capturing the value in a local.
    #[allow(clippy::too_many_arguments)]
    fn emit_integer(
        &mut self,
        key: &str,
        label: &str,
        width: u8,
        signed: Signedness,
        endianness: Option<Endianness>,
        enum_ref: Option<&str>,
        parent: &str,
        indent: usize,
    ) {
        let order = endianness.unwrap_or(self.endianness);
        let little = matches!(order, Endianness::Little);
        let pf_type = proto_int_type(width, signed);
        let label = lua_escape(label);
        let ctor = match enum_ref.and_then(|name| self.value_string_table(name)) {
            Some(table) => format!(
                "ProtoField.{pf_type}(\"{}.{key}\", \"{label}\", base.DEC, {table})",
                self.proto
            ),
            None => format!(
                "ProtoField.{pf_type}(\"{}.{key}\", \"{label}\")",
                self.proto
            ),
        };
        self.register(key, &ctor);

        let reader = int_reader(width, little, signed);
        let var = value_var(key);
        let _ = self.checked_size(&width.to_string(), indent);
        let numeric = if width == 8 { ":tonumber()" } else { "" };
        self.line(
            indent,
            &format!("local {var} = buffer(offset, {width}){reader}{numeric}"),
        );
        let adder = if little { "add_le" } else { "add" };
        self.line(
            indent,
            &format!("{parent}:{adder}(f[\"{key}\"], buffer(offset, {width}))"),
        );
        self.line(indent, &format!("offset = offset + {width}"));
    }

    /// Emit a delimited bytes or string field: scan for the terminator, then add
    /// the value and advance past the terminator. This mirrors the executor's
    /// terminator handling so following fields stay at the right offset instead
    /// of the field swallowing the rest of the packet.
    #[allow(clippy::too_many_arguments)]
    fn emit_delimited(
        &mut self,
        key: &str,
        label: &str,
        is_string: bool,
        terminator: &[u8],
        include: bool,
        parent: &str,
        indent: usize,
    ) {
        let label = lua_escape(label);
        let ctor = if is_string {
            format!("ProtoField.string(\"{}.{key}\", \"{label}\")", self.proto)
        } else {
            format!("ProtoField.bytes(\"{}.{key}\", \"{label}\")", self.proto)
        };
        self.register(key, &ctor);

        let term_len = terminator.len().max(1);
        let mut hex = String::with_capacity(terminator.len() * 2);
        for byte in terminator {
            let _ = write!(hex, "{byte:02X}");
        }
        let dlen = self.temp("dlen");
        let found = self.temp("found");
        self.line(indent, &format!("local {dlen} = 0"));
        self.line(indent, &format!("local {found} = false"));
        self.line(
            indent,
            &format!("while offset + {dlen} + {term_len} <= {} do", self.limit()),
        );
        self.line(
            indent + 1,
            &format!("sextant_work = sextant_work + {term_len}"),
        );
        self.line(
            indent + 1,
            "if sextant_work > 1048576 then error(\"Sextant: delimiter work limit\") end",
        );
        self.line(
            indent + 1,
            &format!("if buffer(offset + {dlen}, {term_len}):bytes():tohex() == \"{hex}\" then"),
        );
        self.line(indent + 2, &format!("{found} = true"));
        self.line(indent + 2, "break");
        self.line(indent + 1, "end");
        self.line(indent + 1, &format!("{dlen} = {dlen} + 1"));
        self.line(indent, "end");
        self.line(
            indent,
            &format!("if not {found} then error(\"Sextant: missing delimiter\") end"),
        );

        let vlen = self.temp("vlen");
        let clen = self.temp("clen");
        self.line(indent, &format!("local {vlen} = {dlen}"));
        self.line(indent, &format!("local {clen} = {dlen}"));
        self.line(indent, &format!("if {found} then"));
        self.line(indent + 1, &format!("{clen} = {dlen} + {term_len}"));
        if include {
            self.line(indent + 1, &format!("{vlen} = {dlen} + {term_len}"));
        }
        self.line(indent, "end");
        self.line(
            indent,
            &format!("{parent}:add(f[\"{key}\"], buffer(offset, {vlen}))"),
        );
        self.line(indent, &format!("offset = offset + {clen}"));
    }

    /// Emit an array as a bounded loop adding to a subtree.
    fn emit_array(
        &mut self,
        label: &str,
        key: &str,
        element: &Field,
        count: &CountRule,
        parent: &str,
        indent: usize,
    ) {
        let arr = self.temp("arr");
        let astart = self.temp("astart");
        let label = lua_escape(label);
        self.line(indent, &format!("local {astart} = offset"));
        let enclosing_limit = self.limit().to_owned();
        self.line(
            indent,
            &format!("local {arr} = {parent}:add(buffer(offset), \"{label}\")"),
        );

        // Build the loop condition from the count rule, capturing the counter
        // local (when there is one) so the loop body can advance it.
        let (cond, counter) = match count {
            CountRule::Fixed { count } => {
                let i = self.temp("i");
                self.line(indent, &format!("local {i} = 0"));
                (format!("{i} < {count}"), Some(i))
            }
            CountRule::FromField { count_field } => {
                let n = value_var(&join_sibling(key, count_field.as_str()));
                self.line(
                    indent,
                    &format!(
                        "if {n} < 0 or {n} > 1048576 then error(\"Sextant: array count limit\") end"
                    ),
                );
                let i = self.temp("i");
                self.line(indent, &format!("local {i} = 0"));
                (format!("{i} < {n}"), Some(i))
            }
            CountRule::BoundedBy { length_field } => {
                let len = value_var(&join_sibling(key, length_field.as_str()));
                let aend = self.temp("aend");
                self.line(indent, &format!("if {len} < 0 or {len} > {enclosing_limit} - offset then error(\"Sextant: array exceeds enclosing boundary\") end"));
                self.line(indent, &format!("local {aend} = offset + {len}"));
                self.limits.push(aend.clone());
                (format!("offset < {aend}"), None)
            }
            CountRule::ToEnd => (format!("offset < {enclosing_limit}"), None),
        };

        self.line(indent, &format!("while {cond} do"));
        self.line(indent + 1, "sextant_work = sextant_work + 1");
        self.line(
            indent + 1,
            "if sextant_work > 1048576 then error(\"Sextant: array work limit\") end",
        );
        let before = self.temp("before");
        self.line(indent + 1, &format!("local {before} = offset"));
        self.emit_element(element, key, &arr, indent + 1);
        self.line(
            indent + 1,
            &format!(
                "if offset <= {before} then error(\"Sextant: array element made no progress\") end"
            ),
        );
        if let Some(counter) = &counter {
            self.line(indent + 1, &format!("{counter} = {counter} + 1"));
        }
        self.line(indent, "end");
        if matches!(count, CountRule::BoundedBy { .. }) {
            self.limits.pop();
        }
        self.line(indent, &format!("{arr}:set_len(offset - {astart})"));
    }

    /// Emit one array element into the array subtree.
    fn emit_element(&mut self, element: &Field, key: &str, arr: &str, indent: usize) {
        match &element.kind {
            Kind::Struct { structure } => {
                let label = lua_escape(&element.name.clone().unwrap_or_else(|| "item".to_owned()));
                let el = self.temp("el");
                let estart = self.temp("estart");
                self.line(indent, &format!("local {estart} = offset"));
                self.line(
                    indent,
                    &format!("local {el} = {arr}:add(buffer(offset), \"{label}\")"),
                );
                self.emit_struct(structure, &el, key, indent);
                self.line(indent, &format!("{el}:set_len(offset - {estart})"));
            }
            Kind::Array {
                element: inner,
                count,
            } => {
                let label = element.name.clone().unwrap_or_else(|| "item".to_owned());
                self.emit_array(&label, key, inner, count, arr, indent);
            }
            _ => {
                let label = element.name.clone().unwrap_or_else(|| "item".to_owned());
                self.emit_value(element, key, &label, arr, parent_prefix(key), indent);
            }
        }
    }

    /// The Lua expression for a field's byte size from its [`SizeRule`].
    fn size_expr(&self, size: Option<&SizeRule>, prefix: &str) -> String {
        match size {
            Some(SizeRule::Fixed { bytes }) => bytes.to_string(),
            Some(SizeRule::Derived { length_field }) => {
                value_var(&join(prefix, &snake(length_field.as_str(), "len")))
            }
            Some(SizeRule::ToEnd) | None | Some(SizeRule::Delimited { .. }) => {
                format!("{} - offset", self.limit())
            }
        }
    }
}

/// Escape a string for safe inclusion in a Lua double-quoted literal.
///
/// Field names, enum variant names, and other labels are derived from untrusted
/// samples and from model responses, both of which may contain a double quote, a
/// backslash, a newline, or other control bytes. A Lua double-quoted literal
/// cannot contain a raw newline and an unescaped quote or backslash would let
/// crafted text break out of the string and inject arbitrary Lua into the
/// generated dissector, which the user runs in Wireshark. This escapes the quote
/// and backslash and renders every control character (and the raw quote and
/// backslash) as a numeric `\ddd` escape so no input can leave the literal.
fn lua_escape(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for ch in text.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            // Other ASCII control characters become numeric escapes; Lua reads
            // `\ddd` as a single byte, keeping the literal well formed.
            c if (c as u32) < 0x20 || c as u32 == 0x7f => {
                let _ = write!(out, "\\{:03}", c as u32);
            }
            c => out.push(c),
        }
    }
    out
}

/// The Wireshark `ProtoField` constructor name for an integer width and sign.
fn proto_int_type(width: u8, signed: Signedness) -> String {
    let bits = u16::from(width.max(1)) * 8;
    match signed {
        Signedness::Unsigned => format!("uint{bits}"),
        Signedness::Signed => format!("int{bits}"),
    }
}

/// The `TvbRange` reader method for an integer width, byte order, and sign, so a
/// captured signed value keeps its sign for any later derived size or count.
fn int_reader(width: u8, little: bool, signed: Signedness) -> &'static str {
    match (width, little, signed) {
        (8, true, Signedness::Signed) => ":le_int64()",
        (8, false, Signedness::Signed) => ":int64()",
        (8, true, Signedness::Unsigned) => ":le_uint64()",
        (8, false, Signedness::Unsigned) => ":uint64()",
        (_, true, Signedness::Signed) => ":le_int()",
        (_, false, Signedness::Signed) => ":int()",
        (_, true, Signedness::Unsigned) => ":le_uint()",
        (_, false, Signedness::Unsigned) => ":uint()",
    }
}

/// The Lua local that holds a field's captured integer value.
fn value_var(key: &str) -> String {
    format!("sextant.v_{}", key.replace('.', "_"))
}

/// Join a dotted-path prefix and a field name.
fn join(prefix: &str, name: &str) -> String {
    if prefix.is_empty() {
        name.to_owned()
    } else {
        format!("{prefix}.{name}")
    }
}

/// The dotted key for a sibling of the field at `key`: the value referenced by a
/// length or count field lives under the same prefix as the array.
fn join_sibling(array_key: &str, ref_name: &str) -> String {
    match array_key.rfind('.') {
        Some(dot) => join(&array_key[..dot], &snake(ref_name, "ref")),
        None => snake(ref_name, "ref"),
    }
}

/// The prefix (all but the last segment) of a dotted key.
fn parent_prefix(key: &str) -> &str {
    match key.rfind('.') {
        Some(dot) => &key[..dot],
        None => "",
    }
}

/// The dissector field name for a field, synthesizing one when unnamed.
fn field_name(field: &Field, index: usize) -> String {
    match &field.name {
        Some(name) => snake(name, &format!("field_{index}")),
        None => format!("field_{index}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tlv_exports_dissector_with_fields_and_loop() {
        let lua = export(&sextant_ir::fixtures::tlv_ground_truth());
        assert!(lua.contains("Proto(\"tlv\""));
        assert!(lua.contains("ProtoField.bytes(\"tlv.magic\""));
        assert!(lua.contains("ProtoField.uint8(\"tlv.version\""));
        // The record loop reads the count and repeats.
        assert!(lua.contains("while"));
        assert!(lua.contains("function proto_tlv.dissector(buffer, pinfo, tree)"));
        // The value size derives from the record length.
        assert!(lua.contains("v_records_length"));
    }

    #[test]
    fn png_exports_to_end_loop() {
        let lua = export(&sextant_ir::fixtures::png_ground_truth());
        assert!(lua.contains("Proto(\"png\""));
        assert!(lua.contains("offset < blen"));
        assert!(lua.contains("ProtoField.string(\"png.chunks.chunk_type\""));
    }

    #[test]
    fn export_is_deterministic() {
        let format = sextant_ir::fixtures::tlv_ground_truth();
        assert_eq!(export(&format), export(&format));
    }

    use sextant_ir::{Bytes, Confidence, EnumVariant, Metadata};

    /// Build a little-endian format from a list of root fields.
    fn format_of(fields: Vec<Field>, enums: BTreeMap<String, EnumDef>) -> Format {
        Format {
            name: "t".to_owned(),
            endianness: Endianness::Little,
            root: Structure::new(fields),
            enums,
            metadata: Metadata::default(),
        }
    }

    #[test]
    fn signed_field_uses_a_signed_reader() {
        let field = Field::new(
            Kind::Integer {
                width: 2,
                signed: Signedness::Signed,
                endianness: None,
            },
            Confidence::CERTAIN,
        )
        .with_name("delta");
        let lua = export(&format_of(vec![field], BTreeMap::new()));
        // A signed value is read with a signed reader so it keeps its sign.
        assert!(lua.contains(":le_int()"), "got:\n{lua}");
        assert!(lua.contains("ProtoField.int16(\"t.delta\""), "got:\n{lua}");
    }

    #[test]
    fn delimited_field_scans_for_its_terminator() {
        let field = Field::new(Kind::Bytes, Confidence::CERTAIN)
            .with_name("name")
            .with_size(SizeRule::Delimited {
                terminator: Bytes::new(vec![0x00]),
                include_terminator: false,
            });
        let lua = export(&format_of(vec![field], BTreeMap::new()));
        // The dissector scans for the terminator rather than reading to end.
        assert!(lua.contains(":bytes():tohex() == \"00\""), "got:\n{lua}");
    }

    #[test]
    fn protocol_metadata_binds_the_dissector_to_its_port() {
        // A format inferred from a capture records its transport and port, so the
        // exporter emits an active DissectorTable registration (Step 11).
        let mut format = format_of(
            vec![
                Field::new(Kind::Bytes, Confidence::CERTAIN)
                    .with_name("payload")
                    .with_size(SizeRule::ToEnd),
            ],
            BTreeMap::new(),
        );
        format
            .metadata
            .extra
            .insert("protocol.transport".to_owned(), "tcp".to_owned());
        format
            .metadata
            .extra
            .insert("protocol.port".to_owned(), "502".to_owned());
        let lua = export(&format);
        assert!(
            lua.contains("DissectorTable.get(\"tcp.port\"):add(502, proto_t)"),
            "got:\n{lua}"
        );
        // The binding is active, not the commented placeholder.
        assert!(
            !lua.contains("-- DissectorTable.get(\"udp.port\")"),
            "got:\n{lua}"
        );
    }

    #[test]
    fn malicious_array_element_name_cannot_inject_lua() {
        // An array element's display label is taken from its raw name, which may
        // come from a hostile model response or a crafted sample. A name carrying
        // a double quote and Lua code must be escaped into the label literal, not
        // injected into the dissector the user loads in Wireshark.
        let element = Field::new(Kind::Bytes, Confidence::CERTAIN)
            .with_name("x\") os.execute(\"id\")--")
            .with_size(SizeRule::Fixed { bytes: 1 });
        let array = Field::new(
            Kind::Array {
                element: Box::new(element),
                count: CountRule::Fixed { count: 1 },
            },
            Confidence::CERTAIN,
        )
        .with_name("items");
        let lua = export(&format_of(vec![array], BTreeMap::new()));
        // The injected quote is escaped, so the label literal stays closed.
        assert!(
            lua.contains("x\\\") os.execute"),
            "name not escaped:\n{lua}"
        );
        // The raw breakout sequence (an unescaped quote then Lua) never appears.
        assert!(
            !lua.contains("\"x\") os.execute"),
            "lua injection in dissector:\n{lua}"
        );
    }

    #[test]
    fn malicious_enum_variant_name_is_escaped() {
        // Enum variant names flow into a Lua value-string table. A newline or
        // quote in a variant name must be escaped so the table stays well formed.
        let mut enums = BTreeMap::new();
        enums.insert(
            "kind".to_owned(),
            EnumDef {
                width: Some(1),
                variants: vec![EnumVariant {
                    value: 1,
                    name: "a\"]=os.execute(\"id\")\n--".to_owned(),
                    description: None,
                }],
            },
        );
        let field = Field::new(
            Kind::Enum {
                enum_ref: "kind".to_owned(),
                width: 1,
                endianness: None,
            },
            Confidence::CERTAIN,
        )
        .with_name("kind");
        let lua = export(&format_of(vec![field], enums));
        // No raw newline survives inside the generated source line.
        assert!(
            !lua.contains("os.execute(\"id\")\n"),
            "unescaped newline in lua:\n{lua}"
        );
        assert!(lua.contains("\\n"), "newline not escaped:\n{lua}");
    }

    #[test]
    fn enum_field_emits_a_value_string_table() {
        let mut enums = BTreeMap::new();
        enums.insert(
            "kind".to_owned(),
            EnumDef {
                width: Some(1),
                variants: vec![
                    EnumVariant {
                        value: 1,
                        name: "alpha".to_owned(),
                        description: None,
                    },
                    EnumVariant {
                        value: 2,
                        name: "beta".to_owned(),
                        description: None,
                    },
                ],
            },
        );
        let field = Field::new(
            Kind::Enum {
                enum_ref: "kind".to_owned(),
                width: 1,
                endianness: None,
            },
            Confidence::CERTAIN,
        )
        .with_name("kind");
        let lua = export(&format_of(vec![field], enums));
        assert!(lua.contains("[1]=\"alpha\""), "got:\n{lua}");
        assert!(lua.contains("[2]=\"beta\""), "got:\n{lua}");
        assert!(lua.contains("base.DEC"), "got:\n{lua}");
    }
}
