//! Wireshark Lua dissector (`.lua`) exporter (FR-37).
//!
//! Unlike the declarative targets, a Wireshark dissector is procedural: a
//! function walks the buffer, advancing an `offset` and adding fields to the
//! dissection tree. This exporter generates that function from the IR. Each
//! integer field's value is captured in a local so a later derived size or count
//! can reference it, arrays become loops, and nested structures become subtrees.
//!
//! The dissector is registered as a [`Proto`] but not bound to a port (file
//! formats have none, and protocols arrive in Step 11); a commented example
//! shows how to attach it. Checksums are not verified, matching the other
//! exporters.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use sextant_ir::{
    CountRule, Endianness, Field, Format, Kind, Signedness, SizeRule, StringEncoding, Structure,
};

use crate::naming::snake;

/// Render `format` as a complete Wireshark Lua dissector.
#[must_use]
pub(crate) fn export(format: &Format) -> String {
    let proto = snake(&format.name, "format");
    let mut emitter = Gen {
        proto: proto.clone(),
        endianness: format.endianness,
        fields: Vec::new(),
        registered: BTreeSet::new(),
        code: String::new(),
        temp: 0,
    };

    // Emit the dissection body first so the field registry is fully populated.
    emitter.emit_struct(&format.root, "subtree", "", 1);
    let body = std::mem::take(&mut emitter.code);

    let mut out = String::new();
    out.push_str("-- Generated by Sextant. Edit freely.\n");
    let _ = writeln!(
        out,
        "local proto_{proto} = Proto(\"{proto}\", \"{proto} (Sextant)\")"
    );
    out.push_str("local f = {}\n");
    for field in &emitter.fields {
        out.push_str(field);
        out.push('\n');
    }
    out.push_str(&format!("proto_{proto}.fields = {{\n"));
    for key in &emitter.field_keys() {
        let _ = writeln!(out, "    f[\"{key}\"],");
    }
    out.push_str("}\n\n");

    let _ = writeln!(out, "function proto_{proto}.dissector(buffer, pinfo, tree)");
    out.push_str("    local blen = buffer:len()\n");
    out.push_str("    if blen == 0 then return end\n");
    let _ = writeln!(out, "    pinfo.cols.protocol = \"{proto}\"");
    let _ = writeln!(
        out,
        "    local subtree = tree:add(proto_{proto}, buffer(), \"{proto}\")"
    );
    out.push_str("    local offset = 0\n");
    out.push_str(&body);
    out.push_str("end\n\n");

    out.push_str("-- To attach this dissector, register it with a DissectorTable, for example:\n");
    let _ = writeln!(
        out,
        "-- DissectorTable.get(\"udp.port\"):add(0, proto_{proto})"
    );
    out
}

/// Mutable state for the recursive code generation.
struct Gen {
    proto: String,
    endianness: Endianness,
    fields: Vec<String>,
    registered: BTreeSet<String>,
    code: String,
    temp: usize,
}

impl Gen {
    /// The registered field keys, in registration order.
    fn field_keys(&self) -> Vec<String> {
        // The registration line is `f["key"] = ...`; recover the key from it.
        self.fields
            .iter()
            .filter_map(|line| {
                let start = line.find('"')? + 1;
                let end = line[start..].find('"')? + start;
                Some(line[start..end].to_owned())
            })
            .collect()
    }

    /// A fresh, unique Lua local name with the given prefix.
    fn temp(&mut self, prefix: &str) -> String {
        self.temp += 1;
        format!("{prefix}_{}", self.temp)
    }

    /// Append a line of generated Lua at `indent` levels of four spaces.
    fn line(&mut self, indent: usize, text: &str) {
        for _ in 0..indent {
            self.code.push_str("    ");
        }
        self.code.push_str(text);
        self.code.push('\n');
    }

    /// Register a [`ProtoField`] once, keyed by its dotted path.
    fn register(&mut self, key: &str, ctor: &str) {
        if self.registered.insert(key.to_owned()) {
            self.fields.push(format!("f[\"{key}\"] = {ctor}"));
        }
    }

    /// Emit code dissecting `structure` into the tree item named `parent`, with
    /// dotted-path `prefix` for field keys.
    fn emit_struct(&mut self, structure: &Structure, parent: &str, prefix: &str, indent: usize) {
        let base = self.temp("base");
        self.line(indent, &format!("local {base} = offset"));
        for (index, field) in structure.fields.iter().enumerate() {
            self.emit_field(field, index, parent, prefix, &base, indent);
        }
    }

    /// Emit one field: honor an explicit offset, then dissect by kind.
    fn emit_field(
        &mut self,
        field: &Field,
        index: usize,
        parent: &str,
        prefix: &str,
        base: &str,
        indent: usize,
    ) {
        let name = field_name(field, index);
        let key = join(prefix, &name);

        match &field.offset {
            Some(sextant_ir::FieldOffset::Absolute { bytes }) => {
                self.line(indent, &format!("offset = {base} + {bytes}"));
            }
            Some(sextant_ir::FieldOffset::Derived { offset_field }) => {
                let var = value_var(&join(prefix, &snake(offset_field.as_str(), "off")));
                self.line(indent, &format!("offset = {base} + {var}"));
            }
            None => {}
        }

        match &field.kind {
            Kind::Struct { structure } => {
                let sub = self.temp("sub");
                let start = self.temp("start");
                self.line(indent, &format!("local {start} = offset"));
                self.line(
                    indent,
                    &format!("local {sub} = {parent}:add(buffer(offset), \"{name}\")"),
                );
                self.emit_struct(structure, &sub, &key, indent);
                self.line(indent, &format!("{sub}:set_len(offset - {start})"));
            }
            Kind::Array { element, count } => {
                self.emit_array(&name, &key, element, count, parent, indent);
            }
            _ => self.emit_value(field, &key, &name, parent, prefix, indent),
        }
    }

    /// Emit a leaf field read (integer, enum, bytes, opaque, or string).
    fn emit_value(
        &mut self,
        field: &Field,
        key: &str,
        label: &str,
        parent: &str,
        prefix: &str,
        indent: usize,
    ) {
        match &field.kind {
            Kind::Integer {
                width,
                signed,
                endianness,
            } => self.emit_integer(
                key,
                label,
                *width,
                *signed,
                *endianness,
                None,
                parent,
                indent,
            ),
            Kind::Enum {
                width, endianness, ..
            } => self.emit_integer(
                key,
                label,
                *width,
                Signedness::Unsigned,
                *endianness,
                Some(field),
                parent,
                indent,
            ),
            Kind::Bytes | Kind::Opaque => {
                let ctor = format!("ProtoField.bytes(\"{}.{key}\", \"{label}\")", self.proto);
                self.register(key, &ctor);
                let size = self.size_expr(field.size.as_ref(), prefix);
                self.line(
                    indent,
                    &format!("{parent}:add(f[\"{key}\"], buffer(offset, {size}))"),
                );
                self.line(indent, &format!("offset = offset + ({size})"));
            }
            Kind::String { encoding } => {
                let ctor = format!("ProtoField.string(\"{}.{key}\", \"{label}\")", self.proto);
                self.register(key, &ctor);
                let size = self.size_expr(field.size.as_ref(), prefix);
                let adder = if matches!(encoding, StringEncoding::Utf16Le) {
                    "add_le"
                } else {
                    "add"
                };
                self.line(
                    indent,
                    &format!("{parent}:{adder}(f[\"{key}\"], buffer(offset, {size}))"),
                );
                self.line(indent, &format!("offset = offset + ({size})"));
            }
            Kind::Struct { .. } | Kind::Array { .. } => {
                // Composite kinds are handled by emit_field, not emit_value.
            }
        }
    }

    /// Emit an integer or enum read, capturing the value in a local.
    #[allow(clippy::too_many_arguments)]
    fn emit_integer(
        &mut self,
        key: &str,
        label: &str,
        width: u8,
        signed: Signedness,
        endianness: Option<Endianness>,
        enum_field: Option<&Field>,
        parent: &str,
        indent: usize,
    ) {
        let order = endianness.unwrap_or(self.endianness);
        let little = matches!(order, Endianness::Little);
        let pf_type = proto_int_type(width, signed);
        let ctor = match enum_field.and_then(value_string_table) {
            Some(table) => format!(
                "ProtoField.{pf_type}(\"{}.{key}\", \"{label}\", base.DEC, {table})",
                self.proto
            ),
            None => format!(
                "ProtoField.{pf_type}(\"{}.{key}\", \"{label}\")",
                self.proto
            ),
        };
        self.register(key, &ctor);

        let reader = int_reader(width, little);
        let var = value_var(key);
        self.line(
            indent,
            &format!("local {var} = buffer(offset, {width}){reader}"),
        );
        let adder = if little { "add_le" } else { "add" };
        self.line(
            indent,
            &format!("{parent}:{adder}(f[\"{key}\"], buffer(offset, {width}))"),
        );
        self.line(indent, &format!("offset = offset + {width}"));
    }

    /// Emit an array as a bounded loop adding to a subtree.
    fn emit_array(
        &mut self,
        label: &str,
        key: &str,
        element: &Field,
        count: &CountRule,
        parent: &str,
        indent: usize,
    ) {
        let arr = self.temp("arr");
        let astart = self.temp("astart");
        self.line(indent, &format!("local {astart} = offset"));
        self.line(
            indent,
            &format!("local {arr} = {parent}:add(buffer(offset), \"{label}\")"),
        );

        // Build the loop condition from the count rule, capturing the counter
        // local (when there is one) so the loop body can advance it.
        let (cond, counter) = match count {
            CountRule::Fixed { count } => {
                let i = self.temp("i");
                self.line(indent, &format!("local {i} = 0"));
                (format!("{i} < {count} and offset < blen"), Some(i))
            }
            CountRule::FromField { count_field } => {
                let n = value_var(&join_sibling(key, count_field.as_str()));
                let i = self.temp("i");
                self.line(indent, &format!("local {i} = 0"));
                (format!("{i} < {n} and offset < blen"), Some(i))
            }
            CountRule::BoundedBy { length_field } => {
                let len = value_var(&join_sibling(key, length_field.as_str()));
                let aend = self.temp("aend");
                self.line(indent, &format!("local {aend} = offset + {len}"));
                (format!("offset < {aend} and offset < blen"), None)
            }
            CountRule::ToEnd => ("offset < blen".to_owned(), None),
        };

        self.line(indent, &format!("while {cond} do"));
        self.emit_element(element, key, &arr, indent + 1);
        if let Some(counter) = &counter {
            self.line(indent + 1, &format!("{counter} = {counter} + 1"));
        }
        self.line(indent, "end");
        self.line(indent, &format!("{arr}:set_len(offset - {astart})"));
    }

    /// Emit one array element into the array subtree.
    fn emit_element(&mut self, element: &Field, key: &str, arr: &str, indent: usize) {
        match &element.kind {
            Kind::Struct { structure } => {
                let label = element.name.clone().unwrap_or_else(|| "item".to_owned());
                let el = self.temp("el");
                let estart = self.temp("estart");
                self.line(indent, &format!("local {estart} = offset"));
                self.line(
                    indent,
                    &format!("local {el} = {arr}:add(buffer(offset), \"{label}\")"),
                );
                self.emit_struct(structure, &el, key, indent);
                self.line(indent, &format!("{el}:set_len(offset - {estart})"));
            }
            Kind::Array {
                element: inner,
                count,
            } => {
                let label = element.name.clone().unwrap_or_else(|| "item".to_owned());
                self.emit_array(&label, key, inner, count, arr, indent);
            }
            _ => {
                let label = element.name.clone().unwrap_or_else(|| "item".to_owned());
                self.emit_value(element, key, &label, arr, parent_prefix(key), indent);
            }
        }
    }

    /// The Lua expression for a field's byte size from its [`SizeRule`].
    fn size_expr(&self, size: Option<&SizeRule>, prefix: &str) -> String {
        match size {
            Some(SizeRule::Fixed { bytes }) => bytes.to_string(),
            Some(SizeRule::Derived { length_field }) => {
                value_var(&join(prefix, &snake(length_field.as_str(), "len")))
            }
            Some(SizeRule::ToEnd) | None => "blen - offset".to_owned(),
            Some(SizeRule::Delimited { .. }) => "blen - offset".to_owned(),
        }
    }
}

/// Build the value-string table literal for an enum field, if its enum defines
/// values. Returns `None` when there is nothing to map (the IR carries enum
/// variants on the [`Format`], not inline, so this is a placeholder for inline
/// variants and currently yields `None`).
fn value_string_table(_field: &Field) -> Option<String> {
    None
}

/// The Wireshark `ProtoField` constructor name for an integer width and sign.
fn proto_int_type(width: u8, signed: Signedness) -> String {
    let bits = u16::from(width.max(1)) * 8;
    match signed {
        Signedness::Unsigned => format!("uint{bits}"),
        Signedness::Signed => format!("int{bits}"),
    }
}

/// The `TvbRange` reader method for an integer width and byte order.
fn int_reader(width: u8, little: bool) -> &'static str {
    match (width, little) {
        (8, true) => ":le_uint64()",
        (8, false) => ":uint64()",
        (_, true) => ":le_uint()",
        (_, false) => ":uint()",
    }
}

/// The Lua local that holds a field's captured integer value.
fn value_var(key: &str) -> String {
    format!("v_{}", key.replace('.', "_"))
}

/// Join a dotted-path prefix and a field name.
fn join(prefix: &str, name: &str) -> String {
    if prefix.is_empty() {
        name.to_owned()
    } else {
        format!("{prefix}.{name}")
    }
}

/// The dotted key for a sibling of the field at `key`: the value referenced by a
/// length or count field lives under the same prefix as the array.
fn join_sibling(array_key: &str, ref_name: &str) -> String {
    match array_key.rfind('.') {
        Some(dot) => join(&array_key[..dot], &snake(ref_name, "ref")),
        None => snake(ref_name, "ref"),
    }
}

/// The prefix (all but the last segment) of a dotted key.
fn parent_prefix(key: &str) -> &str {
    match key.rfind('.') {
        Some(dot) => &key[..dot],
        None => "",
    }
}

/// The dissector field name for a field, synthesizing one when unnamed.
fn field_name(field: &Field, index: usize) -> String {
    match &field.name {
        Some(name) => snake(name, &format!("field_{index}")),
        None => format!("field_{index}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tlv_exports_dissector_with_fields_and_loop() {
        let lua = export(&sextant_ir::fixtures::tlv_ground_truth());
        assert!(lua.contains("Proto(\"tlv\""));
        assert!(lua.contains("ProtoField.bytes(\"tlv.magic\""));
        assert!(lua.contains("ProtoField.uint8(\"tlv.version\""));
        // The record loop reads the count and repeats.
        assert!(lua.contains("while"));
        assert!(lua.contains("function proto_tlv.dissector(buffer, pinfo, tree)"));
        // The value size derives from the record length.
        assert!(lua.contains("v_records_length"));
    }

    #[test]
    fn png_exports_to_end_loop() {
        let lua = export(&sextant_ir::fixtures::png_ground_truth());
        assert!(lua.contains("Proto(\"png\""));
        assert!(lua.contains("offset < blen"));
        assert!(lua.contains("ProtoField.string(\"png.chunks.chunk_type\""));
    }

    #[test]
    fn export_is_deterministic() {
        let format = sextant_ir::fixtures::tlv_ground_truth();
        assert_eq!(export(&format), export(&format));
    }
}
