//! Entry point for the Sextant benchmark harness.
//!
//! Runs statistics-only inference over the ground-truth corpus, computes the PRD
//! Section 15 accuracy metrics, prints a results table, and optionally writes the
//! machine-readable JSON results. With `--check` it exits non-zero if any
//! configured target is missed: this is the regression guard CI runs. With
//! `--write-readme` it regenerates the benchmark block in `README.md` so the
//! published numbers are generated by the harness, never hand-written.
//!
//! Usage:
//!   bench [--corpus <dir>] [--out <results.json>] [--check] [--write-readme]

use std::path::PathBuf;
use std::process::ExitCode;

use bench::{BenchOptions, render_readme_section, render_table, run_benchmark};

/// Markers that delimit the generated benchmark block in `README.md`.
const README_START: &str = "<!-- BENCH:START -->";
const README_END: &str = "<!-- BENCH:END -->";

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let mut options = BenchOptions::default();
    let mut out: Option<PathBuf> = None;
    let mut check = false;
    let mut write_readme = false;

    let mut iter = args.iter();
    while let Some(arg) = iter.next() {
        match arg.as_str() {
            "--corpus" => match iter.next() {
                Some(dir) => options.corpus_dir = PathBuf::from(dir),
                None => return usage_error("--corpus requires a directory"),
            },
            "--out" => match iter.next() {
                Some(path) => out = Some(PathBuf::from(path)),
                None => return usage_error("--out requires a file path"),
            },
            "--check" => check = true,
            "--write-readme" => write_readme = true,
            "-h" | "--help" => {
                print_help();
                return ExitCode::SUCCESS;
            }
            other => return usage_error(&format!("unknown argument `{other}`")),
        }
    }

    let report = match run_benchmark(&options) {
        Ok(report) => report,
        Err(error) => {
            eprintln!("bench: failed to evaluate the corpus: {error}");
            return ExitCode::FAILURE;
        }
    };

    print!("{}", render_table(&report));

    if let Some(path) = &out {
        match report.to_json() {
            Ok(json) => {
                if let Err(error) = std::fs::write(path, format!("{json}\n")) {
                    eprintln!(
                        "bench: could not write results to {}: {error}",
                        path.display()
                    );
                    return ExitCode::FAILURE;
                }
                println!("\nWrote machine-readable results to {}", path.display());
            }
            Err(error) => {
                eprintln!("bench: could not serialize results: {error}");
                return ExitCode::FAILURE;
            }
        }
    }

    if write_readme {
        match update_readme(&render_readme_section(&report)) {
            Ok(path) => println!("Updated the benchmark block in {}", path.display()),
            Err(error) => {
                eprintln!("bench: could not update the README: {error}");
                return ExitCode::FAILURE;
            }
        }
    }

    if check {
        let failures = report.regression_failures();
        if !failures.is_empty() {
            eprintln!("\nbench: regression guard failed:");
            for failure in &failures {
                eprintln!("  {failure}");
            }
            return ExitCode::FAILURE;
        }
        println!("\nRegression guard: all configured targets met.");
    }

    ExitCode::SUCCESS
}

/// Replace the content between the README benchmark markers with `section`.
/// Returns the path written on success.
fn update_readme(section: &str) -> std::io::Result<PathBuf> {
    let path = repo_root().join("README.md");
    let text = std::fs::read_to_string(&path)?;
    let start = text.find(README_START).ok_or_else(|| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("README is missing the {README_START} marker"),
        )
    })?;
    let end = text.find(README_END).ok_or_else(|| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("README is missing the {README_END} marker"),
        )
    })?;
    let body_start = start + README_START.len();
    let mut updated = String::with_capacity(text.len());
    updated.push_str(&text[..body_start]);
    updated.push('\n');
    updated.push_str(section);
    updated.push_str(&text[end..]);
    std::fs::write(&path, updated)?;
    Ok(path)
}

/// The repository root, derived from the bench crate's manifest directory.
fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the bench crate always has a parent directory")
        .to_path_buf()
}

/// Print a usage error and return a failure exit code.
fn usage_error(message: &str) -> ExitCode {
    eprintln!("bench: {message}");
    print_help();
    ExitCode::FAILURE
}

/// Print the help text.
fn print_help() {
    eprintln!(
        "Sextant benchmark harness\n\n\
         Usage: bench [--corpus <dir>] [--out <results.json>] [--check] [--write-readme]\n\n\
         Options:\n  \
         --corpus <dir>      Evaluate this corpus directory (default: repository corpus/)\n  \
         --out <file>        Write machine-readable JSON results to this path\n  \
         --check             Exit non-zero if any configured target is missed (CI guard)\n  \
         --write-readme      Regenerate the benchmark block in README.md\n  \
         -h, --help          Show this help"
    );
}
